Code Generation - Simplify completion pattern
47deg/TBD pull request #90
Opened 2023-03-03 17:56 UTC by diesalbla

We can remove the use of an `isInstanceOf` clause and instead use a typed pattern

2023-03-03 19:58 UTC, jackcviers requested changes

2023-03-03 19:58 UTC, jackcviers commented on continuationsPlugin/src/main/scala/continuations/DefDefTransforms.scala
> +          .appliedTo(tpd.Literal(Constant(0x0))),
👍🏻

2023-03-03 19:58 UTC, jackcviers commented on continuationsPlugin/src/test/scala/continuations/StateMachineFixtures.scala
> +       |                $continuation =|                  x$0
This pipe looks like a typo:

```suggestion
       |                $continuation = x$0
```

2023-03-03 19:59 UTC, jackcviers requested changes
Also needs a scalafmtAll

2023-03-06 09:57 UTC, gregorath commented
yeah I remember I spent quite some time to make this work like this but annoyingly didn't manage to. it looks like it fails in the `GenBCode` phase. happy to help you debug it if you need to see the tree that fails etc. it would be nice if we manage to do it.

2023-03-06 15:30 UTC, jackcviers approved these changes

2023-03-07 10:18 UTC, diesalbla commented
An update on this work: yesterday @gregorath and I started looking at the trees generated by the compiler phases. We found the problem to be in the pattern-matcher. Before this phase, the body . However, within the pattern matcher the variable `x$0` is renamed to a fresh variable `x1`, but _only in the pattern_ itself, not in the body of the first `case`.

2023-03-09 13:59 UTC, jackcviers commented on continuationsPlugin/src/test/scala/continuations/ContinuationsPluginSuite.scala
> +  compilerContextWithContinuationsPlugin.test("debug".only) {
You have to remove the .only to get reports on everything in the checks.

2023-03-09 13:59 UTC, jackcviers commented on continuationsPlugin/src/test/scala/continuations/ContinuationsPluginSuite.scala
> +  compilerContextWithContinuationsPlugin.test("debug".only) {
We should be able to remove the debug test entirely, we have a better handle on how to get the tree outputs at need now.

2023-03-15 17:37 UTC, diesalbla commented
> An update on this work: yesterday @gregorath and I started looking at the trees generated by the compiler phases. We found the problem to be in the pattern-matcher. Before this phase, the body . However, within the pattern matcher the variable x$0 is renamed to a fresh variable x1, but only in the pattern itself, not in the body of the first case.

It seems that by adding an extra wrapper of a `Bind`, with the `Typed` on the right hand side, it now works fine and recognises as a variable (waiting for CI)

2023-03-15 17:51 UTC, merged